config/routes.rb
FfxiiiWeaponUpgradeCalculator::Application.routes.draw do
  resources :weapons
  resources :materials
  resources :characters

  devise_for :users

  root :to => 'page#index'

end

app/models/character.rb
class Character < ActiveRecord::Base
  has_many :weapons
end

app/models/material.rb
class Material < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/weapon.rb
class Weapon < ActiveRecord::Base
  belongs_to :character
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def user_is_admin?
    if user_signed_in? and current_user.admin?
      true
    else
      false
    end
  end
  
  def admin_only
    unless user_is_admin?
      redirect_to root_path, flash[:error] => 'This Area is Accessible only to Admins.'
    end
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_filter :admin_only, :except => [:index, :show]
  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @characters }
    end
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    @character = Character.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/new
  # GET /characters/new.json
  def new
    @character = Character.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/1/edit
  def edit
    @character = Character.find(params[:id])
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(params[:character])

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render json: @character, status: :created, location: @character }
      else
        format.html { render action: "new" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /characters/1
  # PUT /characters/1.json
  def update
    @character = Character.find(params[:id])

    respond_to do |format|
      if @character.update_attributes(params[:character])
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :ok }
    end
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_filter :admin_only, :except => [:index, :show]
  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @materials }
    end
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
    @material = Material.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @material }
    end
  end

  # GET /materials/new
  # GET /materials/new.json
  def new
    @material = Material.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @material }
    end
  end

  # GET /materials/1/edit
  def edit
    @material = Material.find(params[:id])
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(params[:material])

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render json: @material, status: :created, location: @material }
      else
        format.html { render action: "new" }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /materials/1
  # PUT /materials/1.json
  def update
    @material = Material.find(params[:id])

    respond_to do |format|
      if @material.update_attributes(params[:material])
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material = Material.find(params[:id])
    @material.destroy

    respond_to do |format|
      format.html { redirect_to materials_url }
      format.json { head :ok }
    end
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
    @characters = Character.all
  end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  # GET /weapons
  # GET /weapons.json
  def index
    @weapons = Weapon.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @weapons }
    end
  end

  # GET /weapons/1
  # GET /weapons/1.json
  def show
    @weapon = Weapon.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @weapon }
    end
  end

  # GET /weapons/new
  # GET /weapons/new.json
  def new
    @weapon = Weapon.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @weapon }
    end
  end

  # GET /weapons/1/edit
  def edit
    @weapon = Weapon.find(params[:id])
  end

  # POST /weapons
  # POST /weapons.json
  def create
    @weapon = Weapon.new(params[:weapon])

    respond_to do |format|
      if @weapon.save
        format.html { redirect_to @weapon, notice: 'Weapon was successfully created.' }
        format.json { render json: @weapon, status: :created, location: @weapon }
      else
        format.html { render action: "new" }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /weapons/1
  # PUT /weapons/1.json
  def update
    @weapon = Weapon.find(params[:id])

    respond_to do |format|
      if @weapon.update_attributes(params[:weapon])
        format.html { redirect_to @weapon, notice: 'Weapon was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weapons/1
  # DELETE /weapons/1.json
  def destroy
    @weapon = Weapon.find(params[:id])
    @weapon.destroy

    respond_to do |format|
      format.html { redirect_to weapons_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_is_admin?
    if user_signed_in? and current_user.admin?
      true
    else
      false
    end
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @characters.each do |character| %>
  <tr>
    <td><%= character.name %></td>
    <td><%= link_to 'Show', character %></td>
    <td><%= link_to 'Edit', edit_character_path(character) %></td>
    <td><%= link_to 'Destroy', character, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @character.name %>
</p>


<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title FFXIII Weapon Upgrade Calculator
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    %section.content
      = yield
    
    - if user_is_admin?
      %nav.admin-nav
        = link_to "Sign Out", destroy_user_session_path, :method => :delete
        = link_to 'Characters', characters_path
        = link_to 'Weapons', weapons_path

app/views/materials/_form.html.erb
<%= form_for(@material) do |f| %>
  <% if @material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% @material.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :buy %><br />
    <%= f.number_field :buy %>
  </div>
  <div class="field">
    <%= f.label :sell %><br />
    <%= f.number_field :sell %>
  </div>
  <div class="field">
    <%= f.label :store %><br />
    <%= f.text_field :store %>
  </div>
  <div class="field">
    <%= f.label :exp %><br />
    <%= f.number_field :exp %>
  </div>
  <div class="field">
    <%= f.label :multiplier %><br />
    <%= f.number_field :multiplier %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>Editing material</h1>

<%= render 'form' %>

<%= link_to 'Show', @material %> |
<%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<h1>Listing materials</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Buy</th>
    <th>Sell</th>
    <th>Store</th>
    <th>Exp</th>
    <th>Multiplier</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @materials.each do |material| %>
  <tr>
    <td><%= material.name %></td>
    <td><%= material.buy %></td>
    <td><%= material.sell %></td>
    <td><%= material.store %></td>
    <td><%= material.exp %></td>
    <td><%= material.multiplier %></td>
    <td><%= link_to 'Show', material %></td>
    <td><%= link_to 'Edit', edit_material_path(material) %></td>
    <td><%= link_to 'Destroy', material, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Material', new_material_path %>

app/views/materials/new.html.erb
<h1>New material</h1>

<%= render 'form' %>

<%= link_to 'Back', materials_path %>

app/views/materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @material.name %>
</p>

<p>
  <b>Buy:</b>
  <%= @material.buy %>
</p>

<p>
  <b>Sell:</b>
  <%= @material.sell %>
</p>

<p>
  <b>Store:</b>
  <%= @material.store %>
</p>

<p>
  <b>Exp:</b>
  <%= @material.exp %>
</p>

<p>
  <b>Multiplier:</b>
  <%= @material.multiplier %>
</p>


<%= link_to 'Edit', edit_material_path(@material) %> |
<%= link_to 'Back', materials_path %>

app/views/page/index.html.haml
%h2 A Final Fantasy XIII Upgrade Tool
%p This tool is meant to help determine what resources you need to upgrade weapons in a cost effective way. At the moment all calculations are estimates. That will steadily change as I find more data.
%p Lets pick a Character to Start

%nav.characters
  - @characters.each do |character|
    = link_to character.name, character

app/views/weapons/_form.html.haml
= semantic_form_for @weapon do |f|

  - if @weapon.errors.any?
    #error_explanation
      %h2= pluralize(@weapon.errors.count, "error") + " prohibited this weapon from being saved:"
      %ul
        - @weapon.errors.full_messages.each do |msg|
          %li= msg

  %ul.fields
    %li= f.input :name
    %li= f.input :character, :as => :select
    %li= f.input :min_level
    %li= f.input :max_level
    %li= f.input :max_strength
    %li= f.input :max_magic
    %li= f.input :bonus
    %li= f.input :base_exp
    %li= f.input :increment_exp
    %li= f.input :buy
    %li= f.input :sell

  = f.submit

app/views/weapons/edit.html.haml
%h2 Editing weapon

= render 'form'

= link_to 'Show', @weapon
= link_to 'Back', weapons_path

app/views/weapons/index.html.haml
%h2 Listing Weapons

- @weapons.each do |weapon|
  %ul
    %li= weapon.name
    - if weapon.character
      %li=raw "Weapon for #{link_to weapon.character.name, weapon.character}"
    %li= weapon.min_level
    %li= weapon.max_level
    %li= weapon.max_strength
    %li= weapon.max_magic
    %li= weapon.bonus
    %li= weapon.base_exp
    %li= weapon.increment_exp
    %li= weapon.buy
    %li= weapon.sell
    - if user_is_admin?
      %li.admin
        %ul
          %li= link_to 'Show', weapon
          %li= link_to 'Edit', edit_weapon_path(weapon)
          %li= link_to 'Destroy', weapon, confirm: 'Are you sure?', method: :delete

= link_to 'New Weapon', new_weapon_path

app/views/weapons/new.html.erb
<h1>New weapon</h1>

<%= render 'form' %>

<%= link_to 'Back', weapons_path %>

app/views/weapons/show.html.haml
- if notice
  %p#notice= notice
  
%section#weapon
  %h2= @weapon.name
  - if @weapon.character
    %p=raw "Weapon for #{link_to @weapon.character.name, @weapon.character}"
  - if @weapon.min_level
    %p= "Minimum level is #{@weapon.min_level}"
  - if @weapon.max_level
    %p= "Maximum level is #{@weapon.max_level}"
  - if @weapon.max_magic
    %p= "Maximum Magic is #{@weapon.max_magic}"
  - if @weapon.max_strength
    %p= "Maximum Strength is #{@weapon.max_strength}"

/ <p>
/   <b>Bonus:</b>
/   <%= @weapon.bonus %>
/ </p>
/ 
/ <p>
/   <b>Base exp:</b>
/   <%= @weapon.base_exp %>
/ </p>
/ 
/ <p>
/   <b>Increment exp:</b>
/   <%= @weapon.increment_exp %>
/ </p>
/ 
/ <p>
/   <b>Buy:</b>
/   <%= @weapon.buy %>
/ </p>
/ 
/ <p>
/   <b>Sell:</b>
/   <%= @weapon.sell %>
/ </p>


= link_to 'Edit', edit_weapon_path(@weapon)
= link_to 'Back', weapons_path